config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  root :to => "web/boards#show"

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:index, :show]
    end
  end

  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
    resource :password_reset, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :users
  end
end

app/controllers/web/password_resets_controller.rb
class Web::PasswordResetsController < Web::ApplicationController
  def new
    @password_reset = PasswordResetForm.new
  end

  def create
    @password_reset = PasswordResetForm.new(password_reset_params)
    @email = @password_reset.email

    if @password_reset.valid?
      @user = @password_reset.user
      @user.set_password_reset_digest
      UserMailer.with({ user: @user }).password_reset.deliver_now

      redirect_to(new_session_path, notice: 'Password reset instructions were sent to your email address')
    else
      flash[:alert] = 'There is no user with such email'
      render(:new)
    end
  end

  def edit
    get_user
  end

  def update
    get_user

    if @user.update(user_params)
      @user.clear_password_reset_digest
      redirect_to(new_session_path, notice: 'Your password was successfully updated')
    else
      render(:edit)
    end
  end

  private

  def password_reset_params
    params.require(:password_reset_form).permit(:email)
  end

  def get_user
    @user = User.find_by(password_reset_digest: params[:user][:password_reset_digest])

    unless @user.password_reset_period_valid?
      redirect_to(new_session_path, alert: 'Password reset link has expired. Please request another one.')
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/web/password_resets/edit.html.slim
h3 Set a new password for your account

= simple_form_for @user, url: password_reset_path, method: :patch, as: :user do |f|
  = f.hidden_field :password_reset_digest, :value => @user.password_reset_digest
  = f.hidden_field :email, :value => @user.email
  p
    = f.input :password
  p
    = f.input :password_confirmation
  p
    = f.button :submit, "Change password"

app/views/web/password_resets/new.html.slim
h3 Reset password

= simple_form_for @password_reset, url: password_reset_path do |f|
  p
    = f.input :email
  p
    = f.button :submit, "Request password reset"
  | You will receive email message with the link for setting a new password.
  br
  | The link will expire in 24 hours.